import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "New App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-start bg-blue-400 w-full">
        <Link className="px-5 py-2 text-white" href="/">Home</Link>
        <Link className="px-5 py-2 text-white" href="/posts">Posts</Link>
        <Link className="px-5 py-2 text-white" href="/artical">Artical</Link>
        <Link className="px-5 py-2 text-white" href="/artical/feature">Feature</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
